# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d313137dffa8b32a8ddd4c96746fbbf41344675bf210246b28b9a6c4f0e7da4856c7e2bfdffd42d365787e6b8da8f6e73b7953feac582f03316437959a2857d7
  twitter_client_id: QDXWRT2EMNk8M2LqKh9uBZQDI
  twitter_client_key: 1Eb2p6zVqiAJPcihmtKxhjAldFb2RL0c74icdEGFRyYn3Lrv58
  facebook_client_id: 1726993310912846
  facebook_client_key: 09181a42e7cf5f677c07ed8a97d6d2a8

test:
  secret_key_base: d5233aafa7d61629cf0d2b8df25b4483263ecb1a839231f1e7e4fdaea0443485ed3bc8b8b4ea7aa14a8bea11686b24becee9bb7766c01c2c9fae50b440911669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_client_id: <%= ENV["TWITTER_CLIENT_ID"] %>
  twitter_client_key: <%= ENV["TWITTER_CLIENT_KEY"] %>
  facebook_client_id: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_client_key: <%= ENV["FACEBOOK_CLIENT_KEY"] %>8
